"""Near city towers: zones/skyline/near_towers.tscn from tools/city/near_towers.json.

    python tools/props/city.py [--check]

The JSON is the contract shared with the Blender builds (blender/architecture/city/<style>/):
each tower's base center on the street, footprint, roof height and yaw, in Godot world
coordinates. Every tower becomes a Node3D at its base, turned by its yaw, holding the
artist's assets/architecture/city/<name>/<name>.glb, or a placeholder box with the far
city's old facade shader until the glb exists. FarTowers (zones/skyline/far_towers.gd) repeats
these towers across the far city and keeps metadata/footprint's cells clear.

Switching to the real assets is automatic: run this again once the glbs exist, scan in the
editor and force-reload the scene if it's open.

Each style's towers share a few materials (MATERIALS, named by the artist), baked as tiling
sets into assets/architecture/city/_kit/<style>/<material>_<map>.png; every glb embeds a
copy. This writes one shared StandardMaterial3D per name (assets/materials/city/), and,
before the editor first sees new glbs,

    python tools/props/city.py --imports

writes the glbs' .import files (each named material -> its shared .tres, embedded images
discarded) and the kit textures' .import files: one texture set per style in memory. It
skips files that exist; --force overwrites them (e.g. after Godot imported new glbs with its
defaults: no mipmaps, extracted texture copies next to each glb, which then need deleting).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from prop_scenes import ROOT, TEXTURE_IMPORT, Scene, TextResource, glb_import_text, main, v2, write_new_file

SPEC = Path(__file__).resolve().parents[1] / "city" / "near_towers.json"
OUT = "assets/architecture/city"
SCENE = "zones/skyline/near_towers.tscn"
FACADE = "assets/shaders/skyline_facade.gdshader"
MATERIALS_OUT = "assets/materials/city"
# Night emission energies from the artists' reports (KHR_materials_emissive_strength); materials without
# an ORM map get a flat roughness. Day/night (M2 world state) scales the energies together.
MATERIALS = {
    "brutalist": {
        "city_brutal_concrete": {},
        "city_brutal_windows": {"emission": 3.0},
        "city_brutal_metal": {},
        "city_brutal_neon": {"emission": 6.0},
    },
    "spire": {
        "city_spire_glass": {"emission": 2.0},
        "city_spire_metal": {},
        "city_spire_lights": {"emission": 8.0},
        "city_spire_ads": {"emission": 4.0, "roughness": 0.28},
    },
}


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.removeprefix("city_").split("_"))


def near_towers() -> Scene:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    street_y = spec["street_y"]
    s = Scene("NearTowers", "Near ring of the city view, generated by tools/props/city.py from "
              "tools/city/near_towers.json: one node per tower at its base center on the street, turned by its "
              "yaw (local +Z faces the apartment). FarTowers repeats them further out and keeps the cells around metadata/footprint (width, depth) clear.")
    placeholder = None
    for t in spec["towers"]:
        name = pascal(t["name"])
        x, z = t["pos"]
        width, depth = t["footprint"]
        s.node(name, "Node3D", props={"position": (x, street_y, z), "rotation_degrees": (0, t["yaw"], 0),
                                      "metadata/footprint": v2(width, depth)})
        glb = f"{OUT}/{t['name']}/{t['name']}.glb"
        if (ROOT / glb).exists():
            s.instance("Model", glb, parent=name)
        else:
            if placeholder is None:
                placeholder = s.sub("ShaderMaterial", "ShaderMaterial_facade", {"shader": s.ext(FACADE)})
            height = t["top_y"] - street_y
            s.mesh("Placeholder", s.box_mesh((width, height, depth)), parent=name, position=(0, height / 2, 0),
                   material=placeholder, override=True, shadow=False)
    return s


def kit(style: str, material: str, kind: str) -> str | None:
    path = f"{OUT}/_kit/{style}/{material}_{kind}.png"
    return path if (ROOT / path).exists() else None


def material(style: str, name: str, spec: dict) -> TextResource:
    """A shared tower material from the style's kit maps, as Godot imports a glTF material."""
    albedo, orm, normal, emission = (kit(style, name, k) for k in ("albedo", "orm", "normal", "emission"))
    ext, props = [], [f'resource_name = "{name}"']

    def tex(path: str) -> str:
        ext.append(f'[ext_resource type="Texture2D" path="res://{path}" id="{len(ext) + 1}_{Path(path).stem}"]')
        return f'ExtResource("{len(ext)}_{Path(path).stem}")'

    if albedo:
        props.append(f"albedo_texture = {tex(albedo)}")
    if orm:
        orm_ref = tex(orm)
        props += ["metallic = 1.0", f"metallic_texture = {orm_ref}", "metallic_texture_channel = 2",
                  f"roughness_texture = {orm_ref}", "roughness_texture_channel = 1",
                  "ao_enabled = true", f"ao_texture = {orm_ref}", "ao_texture_channel = 0"]
    else:
        props.append(f"roughness = {spec.get('roughness', 1.0)}")
    if normal:
        props += ["normal_enabled = true", f"normal_texture = {tex(normal)}"]
    if emission and "emission" in spec:
        props += ["emission_enabled = true", "emission = Color(0, 0, 0, 1)",
                  f"emission_energy_multiplier = {spec['emission']}", f"emission_texture = {tex(emission)}"]
    head = '[gd_resource type="StandardMaterial3D" format=3]\n\n' + "".join(e + "\n" for e in ext)
    return TextResource(head + ("\n" if ext else "") + "[resource]\n" + "\n".join(props) + "\n")


def materials() -> dict[str, str]:
    """{material name: repo path of its shared .tres}."""
    return {name: f"{MATERIALS_OUT}/{name}.tres" for specs in MATERIALS.values() for name in specs}


def write_imports(force: bool = False) -> int:
    """The kit textures' and the tower glbs' .import files (see the module doc). Returns the count."""
    def write(rel: str, content: str) -> bool:
        if force and (ROOT / rel).exists():
            (ROOT / rel).write_text(content, encoding="utf-8", newline="\n")
            print(f"overwrote {rel}")
            return True
        return write_new_file(rel, content)

    count = 0
    for style, specs in MATERIALS.items():
        for name in specs:
            for kind in ("albedo", "orm", "normal", "emission"):
                if path := kit(style, name, kind):
                    normal = kind == "normal"
                    count += write(path + ".import", TEXTURE_IMPORT.format(
                        path=path, normal_map=1 if normal else 0, roughness_mode=1 if normal else 0))
    shared = materials()
    for t in json.loads(SPEC.read_text(encoding="utf-8"))["towers"]:
        glb = f"{OUT}/{t['name']}/{t['name']}.glb"
        # Only styles whose materials are listed: a later style's glbs must not import unmapped.
        if t["style"] in MATERIALS and (ROOT / glb).exists():
            count += write(glb + ".import", glb_import_text(glb, shared, embedded_images=0))
    return count


def scenes() -> dict:
    out: dict = {SCENE: near_towers()}
    for style, specs in MATERIALS.items():
        for name, spec in specs.items():
            out[f"{MATERIALS_OUT}/{name}.tres"] = material(style, name, spec)
    return out


if __name__ == "__main__":
    if "--imports" in sys.argv[1:]:
        print(f"{write_imports('--force' in sys.argv[1:])} file(s) written")
        sys.exit(0)
    main(scenes)
