@tool
class_name HoloSign
extends Node3D
## A holographic wayfinding sign (D-060; style guide: unshaded, additive, cyan
## or magenta, scanlines, a slight flicker). Origin: the panel's center, +Z
## toward the reader. Built at start from the exports: a panel quad
## (assets/shaders/holo_sign.gdshader: faint fill, outline, chevrons running
## toward [member arrow]) and a Label3D with an MSDF font (crisp at any
## distance), shared by every sign. No per-frame script work: the shader
## animates. Generated by the zone generators (tools/blockout/blockout.py).

const SHADER := preload("res://assets/shaders/holo_sign.gdshader")

enum Arrow { NONE, LEFT, RIGHT }

## Lines of text ("\n" between them).
@export_multiline var text := "":
	set(value):
		text = value
		_rebuild()
@export var tint := Color(0.02, 0.85, 0.91):
	set(value):
		tint = value
		_rebuild()
## Panel size in meters.
@export var size := Vector2(1.0, 0.3):
	set(value):
		size = value
		_rebuild()
@export var arrow := Arrow.NONE:
	set(value):
		arrow = value
		_rebuild()
## Text height of one line (m).
@export_custom(PROPERTY_HINT_NONE, "suffix:m") var line_height := 0.07:
	set(value):
		line_height = value
		_rebuild()
@export var align := HORIZONTAL_ALIGNMENT_CENTER:
	set(value):
		align = value
		_rebuild()

static var _font: SystemFont

var _panel: MeshInstance3D
var _label: Label3D


func _ready() -> void:
	_rebuild()


func _rebuild() -> void:
	if not is_inside_tree():
		return
	if not _font:
		_font = SystemFont.new()
		_font.font_names = PackedStringArray(["Bahnschrift", "Segoe UI", "Arial"])
		_font.multichannel_signed_distance_field = true
	if not _panel:
		_panel = MeshInstance3D.new()
		_panel.name = "Panel"
		_panel.mesh = QuadMesh.new()
		_panel.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		_panel.material_override = ShaderMaterial.new()
		(_panel.material_override as ShaderMaterial).shader = SHADER
		add_child(_panel, false, INTERNAL_MODE_FRONT)
		_label = Label3D.new()
		_label.name = "Text"
		_label.font = _font
		_label.outline_size = 0
		_label.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		_label.render_priority = 1
		_label.double_sided = false
		add_child(_label, false, INTERNAL_MODE_FRONT)
	(_panel.mesh as QuadMesh).size = size
	var mat := _panel.material_override as ShaderMaterial
	mat.set_shader_parameter("tint", tint)
	mat.set_shader_parameter("size", size)
	mat.set_shader_parameter("arrow", {Arrow.NONE: 0.0, Arrow.LEFT: -1.0, Arrow.RIGHT: 1.0}[arrow])
	var arrow_width := minf(0.3, size.x * 0.3) if arrow != Arrow.NONE else 0.0
	mat.set_shader_parameter("arrow_width", arrow_width)
	_label.text = text
	# Font size 64 at this pixel size makes a line about line_height tall.
	_label.font_size = 64
	_label.pixel_size = line_height / 64.0
	_label.modulate = Color(tint.r, tint.g, tint.b).lerp(Color.WHITE, 0.35)
	_label.horizontal_alignment = align
	# The text keeps clear of the chevrons. Label3D anchors left-aligned text at its origin,
	# centered text on it: left text starts at the panel's padding.
	var pad := 0.05
	var x := -arrow_width / 2.0 if arrow == Arrow.RIGHT else (arrow_width / 2.0 if arrow == Arrow.LEFT else 0.0)
	if align == HORIZONTAL_ALIGNMENT_LEFT:
		x = -size.x / 2.0 + pad + (arrow_width if arrow == Arrow.LEFT else 0.0)
	_label.position = Vector3(x, 0.0, 0.002)
