extends SceneTree
## Writes the avatar's scenes from the character's body glb (D-041):
##
##   core/player/avatar/<character>_body.tscn         the body: AvatarBody, BodyIK, Fingertips, finger blend tree
##   core/player/hands/<character>_hand_<side>.tscn   the hand targets: AvatarHand -> Offset -> HandTarget
##
##   "$GODOT4_EDITOR" --headless --path . --script res://tools/player/avatar.gd
##   "$GODOT4_EDITOR" --headless --path . --script res://tools/player/avatar.gd -- --check
##
## HandTarget is the body's hand bone fitted onto the XR Tools hand it replaces
## (D-038; placement on the controller tuned in the headset in M1): the palm
## center (between the wrist and the middle knuckle), the hand's length axis
## and the palm plane (index to little knuckle) of both rest poses are matched,
## the hand keeps its own size. TUNE adds headset corrections on top. The body's
## AnimationTree blends the glb's "Open" to "Grip" per finger group and side
## (<Side>Index, <Side>Middle, <Side>Ring = ring + little, <Side>Thumb), set by
## AvatarHand (D-039). Loads the glbs with GLTFDocument, so it works before the
## editor imports them. AVATAR_GLB=<res path> overrides the body glb (tests).
## --check compares with the files on disk and quits with 1 on a difference.

const CHARACTER := "silena_vesper"
const GLB := "res://assets/characters/%s/%s_body.glb"
const BODY_OUT := "res://core/player/avatar/%s_body.tscn"
const HAND_OUT := "res://core/player/hands/%s_hand_%s.tscn"
const XR_MODEL := "res://addons/godot-xr-tools/hands/model/Hand_Nails_low_%s.gltf"
## The avatar's eye midpoint in the glb's coordinates (the body faces +Z there).
const AVATAR_EYE := Vector3(0.0, 1.7899, 0.1268)
## The boot soles' lowest point in the glb (y); BodyIK lifts the body so it touches the floor.
const SOLE_HEIGHT := -0.012
## Headset corrections of the hand targets in the XR Tools model frame.
const TUNE := {
	"left": {"position": Vector3.ZERO, "rotation_degrees": Vector3.ZERO},
	"right": {"position": Vector3.ZERO, "rotation_degrees": Vector3.ZERO},
}
const SIDES := ["Left", "Right"]
const FINGER_BONES := ["Metacarpal", "Proximal", "Intermediate", "Distal", "Tip"]
## Blend nodes per side in chain order and the fingers each one curls.
const BLENDS := [["Index", ["Index"]], ["Middle", ["Middle"]], ["Ring", ["Ring", "Little"]], ["Thumb", ["Thumb"]]]


func _init() -> void:
	var check := "--check" in OS.get_cmdline_user_args()
	var glb := OS.get_environment("AVATAR_GLB")
	if not glb:
		glb = GLB % [CHARACTER, CHARACTER]
	var body := _load(glb)
	var files := {BODY_OUT % CHARACTER: _body_scene(glb, body)}
	for side: String in SIDES:
		files[HAND_OUT % [CHARACTER, side.to_lower()]] = _hand_scene(side, body)
	body.free()
	var differences := 0
	for path: String in files:
		var text: String = files[path]
		var old := FileAccess.get_file_as_string(path) if FileAccess.file_exists(path) else ""
		if old == text:
			print("UNCHANGED %s" % path)
		elif check:
			print("DIFFERS %s" % path)
			differences += 1
		else:
			DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))
			FileAccess.open(path, FileAccess.WRITE).store_string(text)
			print("WROTE %s" % path)
	quit(differences)


func _body_scene(glb: String, body: Node3D) -> String:
	var lines: PackedStringArray = [
		"[gd_scene format=3]",
		"",
		"[ext_resource type=\"Script\" path=\"res://core/player/avatar/avatar_body.gd\" id=\"1_body\"]",
		"[ext_resource type=\"PackedScene\" path=\"%s\" id=\"2_model\"]" % glb,
		"[ext_resource type=\"Script\" path=\"res://core/player/avatar/body_ik.gd\" id=\"3_ik\"]",
		"[ext_resource type=\"Script\" path=\"res://core/player/avatar/avatar_springs.gd\" id=\"4_springs\"]",
		"",
	]
	lines.append_array(_blend_tree())
	lines.append_array([
		"[sub_resource type=\"SphereShape3D\" id=\"SphereShape3D_fingertip\"]",
		"radius = 0.012",
		"",
		"[node name=\"Avatar\" type=\"Node3D\"]",
		"script = ExtResource(\"1_body\")",
		"metadata/_doc = \"The player's body, %s (D-037, D-041): posed by BodyIK from the headset and the AvatarHand targets, fingers by the hands. Generated by tools/player/avatar.gd; don't edit.\"" % CHARACTER.capitalize(),
		"",
		"[node name=\"Model\" parent=\".\" instance=ExtResource(\"2_model\")]",
		"",
		"[node name=\"BodyIK\" type=\"SkeletonModifier3D\" parent=\"Model/Armature/Skeleton3D\"]",
		"script = ExtResource(\"3_ik\")",
		"eye_rest = %s" % _vec(AVATAR_EYE),
		"sole_height = %s" % _num(SOLE_HEIGHT),
		"",
		"[node name=\"Springs\" type=\"SpringBoneSimulator3D\" parent=\"Model/Armature/Skeleton3D\"]",
		"script = ExtResource(\"4_springs\")",
		"metadata/_doc = \"Coat skirt and belt item spring bones (D-044), after BodyIK.\"",
		"",
	])
	for side: String in SIDES:
		lines.append_array([
			"[node name=\"IndexTip%s\" type=\"BoneAttachment3D\" parent=\"Model/Armature/Skeleton3D\"]" % side,
			"bone_name = \"%sIndexTip\"" % side,
			"",
			"[node name=\"Fingertip\" type=\"Area3D\" parent=\"Model/Armature/Skeleton3D/IndexTip%s\"]" % side,
			"collision_layer = 131072",
			"collision_mask = 0",
			"monitoring = false",
			"metadata/_doc = \"Detection-only %s fingertip on the Player Hands layer: presses XR Tools area buttons (ABPanel, switches) without adding finger collision.\"" % side.to_lower(),
			"",
			"[node name=\"CollisionShape3D\" type=\"CollisionShape3D\" parent=\"Model/Armature/Skeleton3D/IndexTip%s/Fingertip\"]" % side,
			"shape = SubResource(\"SphereShape3D_fingertip\")",
			"",
		])
	lines.append_array([
		"[node name=\"AnimationTree\" type=\"AnimationTree\" parent=\".\"]",
		"root_node = NodePath(\"../Model\")",
		"tree_root = SubResource(\"AnimationNodeBlendTree_fingers\")",
		"anim_player = NodePath(\"../Model/AnimationPlayer\")",
	])
	for side: String in SIDES:
		for blend: Array in BLENDS:
			lines.append("parameters/%s%s/blend_amount = 0.0" % [side, blend[0]])
	lines.append_array(["", "[editable path=\"Model\"]", ""])
	print("body: %d bones, eye %s" % [_skeleton(body).get_bone_count(), _vec(AVATAR_EYE)])
	return "\n".join(lines)


func _hand_scene(side: String, body: Node3D) -> String:
	var s := side.left(1)
	var xr := _load(XR_MODEL % s)
	var body_frame := _palm_frame(body, "%sHand" % side, "%sMiddleProximal" % side, "%sIndexProximal" % side, "%sLittleProximal" % side)
	var xr_frame := _palm_frame(xr, "Wrist_%s" % s, "Middle_Proximal_%s" % s, "Index_Proximal_%s" % s, "Little_Proximal_%s" % s)
	var tune: Dictionary = TUNE[side.to_lower()]
	var tuning := Transform3D(Basis.from_euler((tune["rotation_degrees"] as Vector3) * PI / 180.0), tune["position"])
	var fit := tuning * xr_frame * body_frame.affine_inverse()
	var residuals: PackedStringArray = []
	for pair: Array in [["Hand", "Wrist"], ["IndexProximal", "Index_Proximal"], ["LittleProximal", "Little_Proximal"], ["IndexTip", "Index_Tip"]]:
		var moved := fit * _bone(body, "%s%s" % [side, pair[0]]).origin
		residuals.append("%s %.1f mm" % [pair[1], moved.distance_to(_bone(xr, "%s_%s" % [pair[1], s]).origin) * 1000.0])
	print("%s: off the XR Tools hand: %s" % [side.to_lower(), ", ".join(residuals)])
	xr.free()
	var target := fit * _bone(body, "%sHand" % side)
	return "\n".join(PackedStringArray([
		"[gd_scene format=3]",
		"",
		"[ext_resource type=\"Script\" path=\"res://core/player/hands/avatar_hand.gd\" id=\"1_hand\"]",
		"",
		"[node name=\"%sHand\" type=\"Node3D\"]" % side,
		"script = ExtResource(\"1_hand\")",
		"metadata/_doc = \"Player's %s hand (D-041): XR Tools hand behavior and the target for the avatar body's %sHand bone; finger curls from the controls each finger rests on (D-039). Generated by tools/player/avatar.gd; don't edit.\"" % [side.to_lower(), side],
		"",
		"[node name=\"Offset\" type=\"Node3D\" parent=\".\"]",
		"metadata/_doc = \"Moved to the controller's palm offset by XR Tools at runtime.\"",
		"",
		"[node name=\"HandTarget\" type=\"Marker3D\" parent=\"Offset\"]",
		"position = %s" % _vec(target.origin),
		"rotation_degrees = %s" % _vec(target.basis.get_euler() * 180.0 / PI),
		"gizmo_extents = 0.05",
		"",
		"[node name=\"AnimationTree\" type=\"AnimationTree\" parent=\".\"]",
		"active = false",
		"metadata/_doc = \"Unused: XRToolsHand expects an AnimationTree child; the fingers are animated on the body.\"",
		"",
	]))


## Sub-resources of the body's finger blend tree: "Open", then per side and
## finger group a Blend2 (filtered to its bones) towards "Grip", chained.
func _blend_tree() -> PackedStringArray:
	var lines: PackedStringArray = [
		"[sub_resource type=\"AnimationNodeAnimation\" id=\"AnimationNodeAnimation_open\"]",
		"animation = &\"Open\"",
		"",
	]
	var nodes: PackedStringArray = [
		"[sub_resource type=\"AnimationNodeBlendTree\" id=\"AnimationNodeBlendTree_fingers\"]",
		"nodes/OpenHand/node = SubResource(\"AnimationNodeAnimation_open\")",
		"nodes/OpenHand/position = Vector2(-600, 0)",
	]
	var connections: PackedStringArray = []
	var previous := "OpenHand"
	var i := 0
	for side: String in SIDES:
		for blend: Array in BLENDS:
			var node := "%s%s" % [side, blend[0]]
			var id := node.to_lower()
			var tracks: PackedStringArray = []
			for finger: String in blend[1]:
				for part: String in FINGER_BONES:
					if not (finger == "Thumb" and part == "Intermediate"):
						tracks.append("Armature/Skeleton3D:%s%s%s" % [side, finger, part])
			lines.append_array([
				"[sub_resource type=\"AnimationNodeAnimation\" id=\"AnimationNodeAnimation_grip_%s\"]" % id,
				"animation = &\"Grip\"",
				"",
				"[sub_resource type=\"AnimationNodeBlend2\" id=\"AnimationNodeBlend2_%s\"]" % id,
				"filter_enabled = true",
				"filters = %s" % _string_array(tracks),
				"",
			])
			nodes.append_array([
				"nodes/Closed%s/node = SubResource(\"AnimationNodeAnimation_grip_%s\")" % [node, id],
				"nodes/Closed%s/position = Vector2(%d, 250)" % [node, -400 + 220 * i],
				"nodes/%s/node = SubResource(\"AnimationNodeBlend2_%s\")" % [node, id],
				"nodes/%s/position = Vector2(%d, 0)" % [node, -300 + 220 * i],
			])
			connections.append_array(["&\"%s\", 0, &\"%s\"" % [node, previous], "&\"%s\", 1, &\"Closed%s\"" % [node, node]])
			previous = node
			i += 1
	connections.append("&\"output\", 0, &\"%s\"" % previous)
	nodes.append("node_connections = [%s]" % ", ".join(connections))
	lines.append_array(nodes)
	lines.append("")
	return lines


## Loads a glTF file as a scene (not added to the tree).
func _load(path: String) -> Node3D:
	var doc := GLTFDocument.new()
	var state := GLTFState.new()
	var err := doc.append_from_file(ProjectSettings.globalize_path(path), state)
	assert(err == OK, "can't load %s" % path)
	return doc.generate_scene(state) as Node3D


func _skeleton(scene: Node3D) -> Skeleton3D:
	return scene.find_children("*", "Skeleton3D", true, false)[0]


## Rest pose of a bone in the scene root's frame.
func _bone(scene: Node3D, bone: String) -> Transform3D:
	var skeleton := _skeleton(scene)
	var index := skeleton.find_bone(bone)
	assert(index >= 0, "no bone %s" % bone)
	var local := Transform3D()
	var node: Node = skeleton
	while node != scene:
		local = (node as Node3D).transform * local
		node = node.get_parent()
	return local * skeleton.get_bone_global_rest(index)


## Palm frame: origin between wrist and middle knuckle, X along the hand,
## Y normal to the palm plane (index to little knuckle).
func _palm_frame(scene: Node3D, wrist: String, middle: String, index: String, little: String) -> Transform3D:
	var w := _bone(scene, wrist).origin
	var m := _bone(scene, middle).origin
	var x := (m - w).normalized()
	var y := x.cross(_bone(scene, index).origin - _bone(scene, little).origin).normalized()
	return Transform3D(Basis(x, y, x.cross(y)), (w + m) * 0.5)


func _vec(v: Vector3) -> String:
	return "Vector3(%s, %s, %s)" % [_num(v.x), _num(v.y), _num(v.z)]


func _num(f: float) -> String:
	var r := snappedf(f, 0.0001)
	return str(0.0 if is_zero_approx(r) else r).trim_suffix(".0")


func _string_array(items: PackedStringArray) -> String:
	var quoted: PackedStringArray = []
	for item in items:
		quoted.append("\"%s\"" % item)
	return "[%s]" % ", ".join(quoted)
