"""Generates zones/corridor/corridor.tscn (blockout) from the layout below (D-059).

    python tools/blockout/corridor.py [--check]

Floor 44's corridors, the first zone outside the apartment, streamed in by ZoneStreamer
(zones/zone_graph.json). The zone scene is generated: edit this file, not the .tscn.
Written by tools/blockout/blockout.py (shell, occluders, window notifiers, bounds, props,
signs, lights, probes, entries, perf path).

Layout (x = east, z = south, the facade faces -Z), interior extents:
    side corridor  x  6.6..8.8   z -3.0..7.0   from the facade window (north) past our entrance
                                               (west wall, 4417) and two neighbors (east wall)
    main corridor  x -7.0..21.0  z  7.0..9.4   behind the units: four doors south, service north,
                                               stairs at the west end
    elevator lobby x 11.0..15.0  z  9.6..12.0  off the main corridor's south side, two elevators

The side corridor's west wall is the apartment's east wall (line x 6.5). The corridor has its
own copy of it (same line, same door gap), so it stays closed while the apartment isn't loaded;
both are world-mapped plaster (D-035), so where they overlap they look the same.

Elevators, call buttons and the stairs are static placeholders until the elevator step (M3).
Signs and unit numbers are Label3D placeholders until the world directory (roadmap).
"""

import math
import sys

from blockout import T, Zone, door_gap

H = 2.8  # ceiling height
NORTH = -3.1  # facade wall line (the apartment's window wall)
WEST = 6.5  # side corridor west wall line = the apartment's east wall
EAST = 8.9  # side corridor east wall line
MAIN_N, MAIN_S = 6.9, 9.5  # main corridor wall lines
MAIN_W, MAIN_E = -7.1, 21.1  # main corridor end wall lines
LOBBY_W, LOBBY_E, LOBBY_S = 10.9, 15.1, 12.1
SIDE_X = (WEST + EAST) / 2  # 7.7
MAIN_Z = (MAIN_N + MAIN_S) / 2  # 8.2
LOBBY_X = (LOBBY_W + LOBBY_E) / 2  # 13.0
ELEVATORS = [12.0, 14.0]  # door centers on the lobby's south wall
ELEVATOR_W, ELEVATOR_H = 1.1, 2.2

# Neighbor doors: name, wall ("x"/"z" axis), wall line, position along the wall, yaw (local +Z = the unit), label.
DOORS = [
    ("Door4418", "z", EAST, 0.0, 90, "4418"),
    ("Door4419", "z", EAST, 4.6, 90, "4419"),
    ("Door4420", "x", MAIN_S, 18.0, 0, "4420"),
    ("Door4421", "x", MAIN_S, 5.0, 0, "4421"),
    ("Door4422", "x", MAIN_S, 1.0, 0, "4422"),
    ("Door4423", "x", MAIN_S, -4.0, 0, "4423"),
    ("DoorService", "x", MAIN_N, 4.6, 180, "SERVICE"),
    ("DoorStairs", "z", MAIN_W, MAIN_Z, -90, "STAIRS"),
]
DOOR_HALF = 0.45
# The leaf's unit plate (reads 4417, built into the leaf glb) in the door's frame (origin bottom center of
# the opening on the wall's center plane, +Z = the unit): a cover over it and the door's own number in front.
NUMBER_PLATE = (0.0, 1.73, 0.041)
PLATE_COVER = (0.25, 0.115, 0.006)


def door_point(pos, yaw, local):
    """A point in a door's frame (yaw about Y, degrees) in world coordinates."""
    c, s = math.cos(math.radians(yaw)), math.sin(math.radians(yaw))
    x, y, z = local
    return (round(pos[0] + x * c + z * s, 4), round(pos[1] + y, 4), round(pos[2] - x * s + z * c, 4))


def door_size(yaw, size):
    """A box size in a door's frame turned by a multiple of 90 degrees."""
    return size if round(yaw / 90) % 2 == 0 else (size[2], size[1], size[0])


def build() -> Zone:
    z = Zone("Corridor", "zones/corridor/corridor.tscn", height=H, doc=(
        "Zone: corridor, floor 44 (side corridor with the facade window and our entrance, main corridor, elevator "
        "lobby). GENERATED by tools/blockout/corridor.py; edit that, not this file. Floor y 0, ceiling 2.8 m. "
        "Streamed in by ZoneStreamer (D-059)."))

    # --- Shell: floors and ceilings on the wall center lines -----------------------------------------
    for name, x0, x1, z0, z1, mat in [
        ("Side", WEST, EAST, NORTH, MAIN_N, "concrete"),
        ("Main", MAIN_W, MAIN_E, MAIN_N, MAIN_S, "concrete"),
        ("Lobby", LOBBY_W, LOBBY_E, MAIN_S, LOBBY_S, "concrete"),
    ]:
        center, size = ((x0 + x1) / 2, (z0 + z1) / 2), (x1 - x0, z1 - z0)
        z.box("Shell", f"{name}Floor", (center[0], -0.1, center[1]), (size[0], 0.2, size[1]), mat)
        z.box("Shell", f"{name}Ceiling", (center[0], H + 0.1, center[1]), (size[0], 0.2, size[1]), "ceiling")

    gaps = {}
    for name, axis, line, at, yaw, _ in DOORS:
        gaps.setdefault((axis, line), []).append(door_gap(at - DOOR_HALF, at + DOOR_HALF))

    # Side corridor. West: the apartment's east wall line with its entrance gap (apartment.py: East).
    z.wall("Shell", "SideWest", "z", WEST, (NORTH - T / 2, MAIN_N - T / 2), [door_gap(2.45, 3.35)])
    z.wall("Shell", "SideEast", "z", EAST, (NORTH - T / 2, MAIN_N - T / 2), gaps[("z", EAST)])
    z.wall("Shell", "Facade", "x", NORTH, (WEST + T / 2, EAST + T / 2), [z.window_gap("corridor_end", SIDE_X)])
    z.window("corridor_end", "EndWindow", (SIDE_X, 0, NORTH))
    # Main corridor: north wall on both sides of the side corridor, south wall with the lobby opening.
    service = gaps[("x", MAIN_N)]
    z.wall("Shell", "MainNorthWest", "x", MAIN_N, (MAIN_W - T / 2, WEST + T / 2), service)
    z.wall("Shell", "MainNorthEast", "x", MAIN_N, (EAST - T / 2, MAIN_E + T / 2))
    z.wall("Shell", "MainSouth", "x", MAIN_S, (MAIN_W - T / 2, MAIN_E + T / 2),
           gaps[("x", MAIN_S)] + [(LOBBY_W + T / 2, LOBBY_E - T / 2, 0.0, 2.4)])
    z.wall("Shell", "MainWestEnd", "z", MAIN_W, (MAIN_N - T / 2, MAIN_S + T / 2), gaps[("z", MAIN_W)])
    z.wall("Shell", "MainEastEnd", "z", MAIN_E, (MAIN_N - T / 2, MAIN_S + T / 2))
    # Elevator lobby.
    z.wall("Shell", "LobbyWest", "z", LOBBY_W, (MAIN_S + T / 2, LOBBY_S + T / 2))
    z.wall("Shell", "LobbyEast", "z", LOBBY_E, (MAIN_S + T / 2, LOBBY_S + T / 2))
    z.wall("Shell", "LobbySouth", "x", LOBBY_S, (LOBBY_W - T / 2, LOBBY_E + T / 2),
           [(x - ELEVATOR_W / 2, x + ELEVATOR_W / 2, 0.0, ELEVATOR_H) for x in ELEVATORS])

    # --- Elevators (placeholders): steel leaves in the openings, gunmetal trim, a call panel -----------
    face = LOBBY_S - T / 2  # the lobby side of the south wall
    for i, x in enumerate(ELEVATORS):
        half = ELEVATOR_W / 2
        z.box("Elevators", f"Car{i}DoorLeft", (x - half / 2, ELEVATOR_H / 2, LOBBY_S), (half - 0.005, ELEVATOR_H, 0.04), "steel")
        z.box("Elevators", f"Car{i}DoorRight", (x + half / 2, ELEVATOR_H / 2, LOBBY_S), (half - 0.005, ELEVATOR_H, 0.04), "steel")
        z.box("Elevators", f"Car{i}TrimLeft", (x - half - 0.03, ELEVATOR_H / 2, face - 0.01), (0.06, ELEVATOR_H, 0.02), "gunmetal", False)
        z.box("Elevators", f"Car{i}TrimRight", (x + half + 0.03, ELEVATOR_H / 2, face - 0.01), (0.06, ELEVATOR_H, 0.02), "gunmetal", False)
        z.box("Elevators", f"Car{i}TrimTop", (x, ELEVATOR_H + 0.03, face - 0.01), (ELEVATOR_W + 0.12, 0.06, 0.02), "gunmetal", False)
        z.sign(f"Car{i}Floor", (x, ELEVATOR_H + 0.22, face - 0.005), 180, "44", font_size=96, pixel_size=0.0012,
               col=(0.3, 0.95, 1.0))
    z.box("Elevators", "CallPanel", (LOBBY_X, 1.2, face - 0.01), (0.12, 0.26, 0.02), "gunmetal", False)
    z.box("Elevators", "CallUp", (LOBBY_X, 1.25, face - 0.022), (0.03, 0.03, 0.006), "cyan", False)
    z.box("Elevators", "CallDown", (LOBBY_X, 1.15, face - 0.022), (0.03, 0.03, 0.006), "cyan", False)

    # --- Neighbor doors and their numbers ---------------------------------------------------------------
    for name, axis, line, at, yaw, label in DOORS:
        pos = (line, 0, at) if axis == "z" else (at, 0, line)
        z.instance(name, "door_neighbor", pos, (0, yaw, 0))
        px, py, pz = NUMBER_PLATE
        z.box("Plates", f"{name}Plate", door_point(pos, yaw, (px, py, pz - PLATE_COVER[2] / 2 - 0.003)),
              door_size(yaw, PLATE_COVER), "dark", False)
        z.sign(f"{name}Number", door_point(pos, yaw, (px, py, pz - PLATE_COVER[2] - 0.0035)), (yaw + 180) % 360,
               label, font_size=96 if len(label) <= 4 else 64, pixel_size=0.0006, col=(0.92, 0.9, 0.85), lit=False)

    # --- Light fixtures, accents ---------------------------------------------------------------------------
    side_lights = [-1.5, 2.0, 5.2]
    main_lights = [-5.0, 0.0, 4.5, 9.5, 17.5]
    for i, zz in enumerate(side_lights):
        z.box("Fixtures", f"SideLamp{i}", (SIDE_X, H - 0.015, zz), (0.3, 0.03, 0.9), "lamp", False)
    for i, x in enumerate(main_lights):
        z.box("Fixtures", f"MainLamp{i}", (x, H - 0.015, MAIN_Z), (0.9, 0.03, 0.3), "lamp", False)
    z.box("Fixtures", "LobbyLamp", (LOBBY_X, H - 0.015, 10.8), (1.2, 0.03, 0.6), "lamp", False)
    # A cyan cove along the side corridor's east wall, a magenta band over the lobby opening.
    z.box("Fixtures", "SideCove", (EAST - T / 2 - 0.01, 2.55, (NORTH + MAIN_N) / 2 + 0.1), (0.02, 0.025, 9.6), "cyan", False)
    z.box("Fixtures", "LobbyBand", (LOBBY_X, 2.42, MAIN_S - T / 2 - 0.01), (4.0, 0.025, 0.02), "magenta", False)

    # --- Signs ---------------------------------------------------------------------------------------------------
    south_face = MAIN_S - T / 2 - 0.005
    z.sign("Junction", (SIDE_X, 1.85, south_face), 180, "<  4421 - 4423  ·  STAIRS\nELEVATORS  ·  4420  >",
           font_size=72, pixel_size=0.0012)
    z.sign("Elevators", (LOBBY_X, 2.6, south_face), 180, "ELEVATORS", font_size=96, pixel_size=0.0016,
           col=(1.0, 0.45, 0.8))
    z.sign("Directory", (LOBBY_W + T / 2 + 0.005, 1.55, 10.8), 90,
           "FLOOR 44\n\n4417 - 4419   north wing\n4420 - 4423   main corridor\nSTAIRS  ·  SERVICE   west",
           font_size=64, pixel_size=0.0011, align="left")

    # --- Lighting -----------------------------------------------------------------------------------------------
    cool = (0.8, 0.9, 1.0)
    for i, zz in enumerate(side_lights):
        z.light(f"Side{i}", "Omni", (SIDE_X, H - 0.15, zz), color=cool, energy=0.55, range=3.6)
    for i, x in enumerate(main_lights):
        z.light(f"Main{i}", "Omni", (x, H - 0.15, MAIN_Z), color=cool, energy=0.55, range=3.8)
    z.light("Lobby", "Omni", (LOBBY_X, H - 0.15, 10.8), color=(1.0, 0.86, 0.95), energy=0.7, range=4.0)
    z.probe("SideProbe", (SIDE_X, 1.4, (NORTH + MAIN_N) / 2), (EAST - WEST - T, H, MAIN_N - NORTH), daylight=True)
    z.probe("MainProbe", ((MAIN_W + MAIN_E) / 2, 1.4, MAIN_Z), (MAIN_E - MAIN_W - T, H, MAIN_S - MAIN_N - T))
    z.probe("LobbyProbe", (LOBBY_X, 1.4, (MAIN_S + LOBBY_S) / 2), (LOBBY_E - LOBBY_W - T, H, LOBBY_S - MAIN_S))

    # --- Entries and the perf path (eye height 1.7, yaw 0 = -Z, 90 = -X, 180 = +Z, -90 = +X) -------------------
    z.entry("ApartmentDoor", (7.4, 0, 2.9), 90)
    z.entry("Elevator", (LOBBY_X, 0, 11.2), 0)
    for pos, rot in [
        ((SIDE_X, 1.7, 6.0), (0, 0, 0)),
        ((SIDE_X, 1.7, 0.0), (0, 0, 0)),
        ((SIDE_X, 1.7, -2.0), (-5, 0, 0)),
        ((SIDE_X, 1.7, 2.9), (0, 90, 0)),
        ((SIDE_X, 1.7, MAIN_Z), (0, 180, 0)),
        ((1.0, 1.7, MAIN_Z), (0, 90, 0)),
        ((LOBBY_X, 1.7, MAIN_Z), (0, -90, 0)),
        ((LOBBY_X, 1.7, 10.8), (0, 180, 0)),
        ((18.0, 1.7, MAIN_Z), (0, -90, 0)),
    ]:
        z.perf_marker(pos, rot)
    return z


if __name__ == "__main__":
    sys.exit(build().save(check="--check" in sys.argv))
