"""Generates floor 44's neighbor units: zones/units/unit_<number>.tscn (blockout, D-062).

    python tools/blockout/units.py [--check]

Each unit is its own zone in zones/zone_graph.json, keyed by its number, so one unit's scene can be
swapped for another later. Units are built from two templates on the shared writer
(tools/blockout/blockout.py), furnished with the existing props and their variants, in a local frame:

    lx across the unit (0..W, wall center lines), lz from the corridor wall (lz 0) to the facade (lz D);
    the front door is in the corridor wall at lx = door (it belongs to the corridor zone: Props/Door<number>);
    the frame turns by `yaw` (0 or 90) about its origin, the world point of local (0, 0).

    studio  the south units (D 7.1): bathroom beside the entry, kitchenette along the other side wall,
            an open living and sleeping room at the facade window (4420 also has an east window)
    loft    4418 and 4419 (W 5.0, D 12.3, turned 90: they run east from the side corridor): bathroom and
            kitchen at the entry, dining, then living and sleeping toward the east window (4418 also has
            a north window along its living room)

Every unit owns all four of its walls (the corridor and neighbor walls too: copies on the same lines, world-
mapped plaster, D-059), so it stays closed while its neighbors are hidden or not loaded.
"""

import sys

from blockout import ROOT, T, Zone, door_gap

H = 2.6
BATH_D = 2.6       # bathroom depth from the corridor wall (wall center lines)
BATH_W = 2.4       # bathroom width
SOUTH_D = 7.1      # main corridor south wall (z 9.5) to the south facade (z 16.6)
LOFT = (5.0, 12.3)  # side corridor east wall (x 8.9) to the east facade (x 21.2); 5 m between unit walls

# number, origin (world x, z of local 0, 0), yaw, width, depth, door lx, template, options
UNITS = [
    ("4418", (8.9, 1.9), 90, *LOFT, 1.9, "loft",
     {"north_window": True, "sofa": "sofa", "bed": "bed_padded", "wardrobe": "wardrobe", "nightstand": "nightstand_square"}),
    ("4419", (8.9, 6.9), 90, *LOFT, 2.3, "loft",
     {"bath_w": 2.15, "sofa": "sofa_boucle", "bed": "bed", "wardrobe": "wardrobe_lit", "nightstand": "nightstand"}),
    ("4420", (15.1, 9.5), 0, 6.1, SOUTH_D, 3.1, "studio",
     {"east_window": True, "sofa": "sofa_boucle", "bed": "bed", "wardrobe": "wardrobe", "nightstand": "nightstand"}),
    ("4421", (4.4, 9.5), 0, 6.5, SOUTH_D, 1.8, "studio",
     {"sofa": "sofa", "bed": "bed_padded", "wardrobe": "wardrobe_lit", "nightstand": "nightstand_square"}),
    ("4422", (-1.0, 9.5), 0, 5.4, SOUTH_D, 2.0, "studio",
     {"sofa": "sofa_boucle", "bed": "bed_padded", "wardrobe": "wardrobe", "nightstand": "nightstand"}),
    ("4423", (-7.1, 9.5), 0, 6.1, SOUTH_D, 3.1, "studio",
     {"sofa": "sofa", "bed": "bed", "wardrobe": "wardrobe_lit", "nightstand": "nightstand_square"}),
]
WARM = (1, 0.8, 0.6)
COOL = (0.85, 0.93, 1)


def r(v):
    return round(v, 4) + 0.0


class Unit:
    """A unit zone in its local frame (see the module doc)."""

    def __init__(self, number, origin, yaw, width, depth, door):
        self.number, self.yaw, self.W, self.D, self.door = number, yaw, width, depth, door
        self.ox, self.oz = origin
        self.z = Zone(f"Unit{number}", f"zones/units/unit_{number}.tscn", height=H, doc=(
            f"Zone: unit {number}, floor 44 (D-062). GENERATED by tools/blockout/units.py; edit that, not this file. "
            f"Floor y 0, ceiling {H} m. Its front door is the corridor's Props/Door{number}; streamed in by "
            "ZoneStreamer when the player nears it (zones/zone_graph.json)."))

    # -- frame
    def p(self, lx, y, lz):
        if self.yaw == 0:
            return (r(self.ox + lx), r(y), r(self.oz + lz))
        return (r(self.ox + lz), r(y), r(self.oz - lx))  # yaw 90: local +X is world -Z, local +Z world +X

    def s(self, sx, sy, sz):
        return (r(sx), r(sy), r(sz)) if self.yaw == 0 else (r(sz), r(sy), r(sx))

    def turn(self, local_yaw):
        return (self.yaw + local_yaw) % 360

    # -- layout
    def box(self, group, name, center, size, mat, collide=True):
        self.z.box(group, name, self.p(*center), self.s(*size), mat, collide)

    def wall(self, name, axis, line, span, openings=()):
        """axis 'x': along local x at lz = line; 'z': along local z at lx = line; floor to ceiling."""
        cursor, i = span[0], 0

        def put(n, s, e, y0, y1):
            if e - s < 1e-3 or y1 - y0 < 1e-3:
                return
            mid, length, cy, hy = (s + e) / 2, e - s, (y0 + y1) / 2, y1 - y0
            if axis == "x":
                self.box("Shell", n, (mid, cy, line), (length, hy, T), "wall")
            else:
                self.box("Shell", n, (line, cy, mid), (T, hy, length), "wall")

        for s, e, bottom, top in sorted(openings):
            put(f"{name}{i}", cursor, s, 0, H)
            put(f"{name}{i}Below", s, e, 0, bottom)
            put(f"{name}{i}Above", s, e, top, H)
            cursor, i = e, i + 1
        put(f"{name}{i}", cursor, span[1], 0, H)

    def prop(self, name, key, at, local_yaw=0, meta=None):
        self.z.instance(name, key, self.p(*at), (0, self.turn(local_yaw), 0), meta)

    def window(self, spec, name, at, local_yaw):
        self.z.window(spec, name, self.p(at[0], 0, at[1]), self.turn(local_yaw))

    def light(self, name, at, color, energy, rng, shadow=False):
        self.z.light(name, "Omni", self.p(*at), color=color, energy=energy, range=rng, shadow=shadow)
        self.box("Fixtures", f"{name}Disc", (at[0], H - 0.015, at[2]), (0.45, 0.03, 0.45), "lamp", False)

    def probe(self, name, center, size, blend=None, daylight=False):
        self.z.probe(name, self.p(*center), self.s(*size), blend, daylight=daylight)


def build_unit(number, origin, yaw, W, D, door, template, opts) -> Zone:
    u = Unit(number, origin, yaw, W, D, door)
    loft = template == "loft"
    bath_w = opts.get("bath_w", BATH_W)
    bath_d = 2.8 if loft else BATH_D
    # The bathroom goes to the side away from the door; the kitchenette along the other side wall.
    bath_low = door > W / 2
    mx = (lambda lx: lx) if bath_low else (lambda lx: W - lx)        # bath side
    kx = (lambda lx: W - lx) if bath_low else (lambda lx: lx)        # kitchen side
    face_bath = 90 if bath_low else -90                               # props against the bath-side wall face +-lx
    face_kitchen = -face_bath
    bx0, bx1 = (0, bath_w) if bath_low else (W - bath_w, W)

    # --- Floors (split on the wall center lines), ceiling --------------------------------------------
    u.box("Shell", "BathFloor", ((bx0 + bx1) / 2, -0.1, bath_d / 2), (bx1 - bx0, 0.2, bath_d), "concrete")
    ex0, ex1 = (bath_w, W) if bath_low else (0, W - bath_w)
    u.box("Shell", "EntryFloor", ((ex0 + ex1) / 2, -0.1, bath_d / 2), (ex1 - ex0, 0.2, bath_d), "vinyl")
    u.box("Shell", "Floor", (W / 2, -0.1, (bath_d + D) / 2), (W, 0.2, D - bath_d), "carpet" if not loft else "vinyl")
    u.box("Shell", "Ceiling", (W / 2, H + 0.1, D / 2), (W, 0.2, D), "ceiling")

    # --- Walls: corridor (with the front door's opening), facade, sides, bathroom --------------------
    u.wall("Corridor", "x", 0, (-T / 2, W + T / 2), [door_gap(door - 0.45, door + 0.45)])
    facade = []
    if loft:
        facade.append(("apartment_bedroom", "EastWindow", 3.2))
    elif W >= 6.0:
        facade.append(("apartment_living", "Window", W / 2))
    else:
        facade.append(("apartment_bedroom", "Window", W / 2))
    u.wall("Facade", "x", D, (-T / 2, W + T / 2), [u.z.window_gap(spec, x) for spec, _, x in facade])
    for spec, name, x in facade:
        u.window(spec, name, (x, D), 180)
    side_windows = []
    if opts.get("north_window"):  # 4418: the living room's long north wall
        side_windows.append(("apartment_living", "NorthWindow", 9.0))
    if opts.get("east_window"):   # 4420: the corner
        side_windows.append(("apartment_bedroom", "EastWindow", 4.9))
    u.wall("SideLow", "z", 0, (T / 2, D - T / 2))
    u.wall("SideHigh", "z", W, (T / 2, D - T / 2), [u.z.window_gap(spec, at) for spec, _, at in side_windows])
    for spec, name, at in side_windows:
        u.window(spec, name, (W, at), -90)
    bath_door = 1.5
    if bath_low:
        u.wall("BathEnd", "x", bath_d, (T / 2, bath_w + T / 2))
    else:
        u.wall("BathEnd", "x", bath_d, (W - bath_w - T / 2, W - T / 2))
    u.wall("BathSide", "z", mx(bath_w), (T / 2, bath_d - T / 2), [door_gap(bath_door - 0.45, bath_door + 0.45)])

    # --- Bathroom: toilet at the corridor wall, vanity and mirror on the outer side wall --------------
    u.prop("DoorBathroom", "door_bath", (mx(bath_w), 0, bath_door), -face_bath)
    u.prop("Toilet", "toilet", (mx(0.9), 0, T / 2), 0)
    u.prop("Vanity", "vanity", (mx(T / 2), 0, 1.75), face_bath)
    u.prop("BathMirror", "bath_mirror", (mx(T / 2), 1.18, 1.75), face_bath)

    # --- Kitchenette along the other side wall, from the corridor wall ---------------------------------
    k0, k1 = 0.3, 2.6
    u.box("Kitchen", "CounterBody", (kx(0.4), 0.44, (k0 + k1) / 2), (0.6, 0.88, k1 - k0), "dark")
    u.box("Kitchen", "CounterTop", (kx(0.42), 0.9, (k0 + k1) / 2), (0.64, 0.04, k1 - k0 + 0.04), "steel")
    u.box("Kitchen", "CounterNeon", (kx(0.11), 1.56, (k0 + k1) / 2), (0.02, 0.02, k1 - k0 - 0.2), "cyan", False)
    u.prop("Fridge", "fridge", (kx(0.43), 0, 3.0), face_kitchen)
    u.prop("CanCounter", "can", (kx(0.35), 0.922, 1.0))
    u.prop("TrashCan", "trash", (kx(0.3), 0, 3.6))

    # --- Living and sleeping --------------------------------------------------------------------------
    u.prop("Wardrobe", opts["wardrobe"], (mx(1.2), 0, bath_d + T / 2 + 0.3), 0)
    if loft:
        # Dining in the middle, sofa toward the window, the bed at the far end on the kitchen side.
        u.box("Living", "TableTop", (W / 2, 0.73, 5.2), (0.9, 0.04, 0.9), "wood", ((W / 2, 0.375, 5.2), (0.9, 0.75, 0.9)))
        u.box("Living", "TablePedestal", (W / 2, 0.36, 5.2), (0.1, 0.7, 0.1), "steel", False)
        u.prop("CanTable", "can", (W / 2 + 0.15, 0.812, 5.1))
        u.prop("Sofa", opts["sofa"], (W / 2, 0, 7.6), 0)
        u.box("Living", "CoffeeTable", (W / 2, 0.2, 8.8), (1.0, 0.4, 0.5), "dark", True)
        bed_at, stand_at = (kx(1.17), 0, D - T / 2 - 1.0), (kx(0.33), 0, D - T / 2 - 2.15)
    else:
        u.prop("Sofa", opts["sofa"], (kx(1.5), 0, 4.3), 0)
        u.box("Living", "CoffeeTable", (kx(1.5), 0.2, 5.5), (1.0, 0.4, 0.5), "dark", True)
        u.prop("CanTable", "can", (kx(1.4), 0.412, 5.5))
        bed_at, stand_at = (mx(1.17), 0, D - T / 2 - 0.95), (mx(0.33), 0, D - T / 2 - 2.15)
    bed_face = face_kitchen if loft else face_bath  # the bed's head (-Z) toward its side wall
    u.prop("Bed", opts["bed"], bed_at, bed_face)
    u.prop("Nightstand", opts["nightstand"], stand_at, bed_face)

    # --- Light: the living room light casts the unit's one shadow ------------------------------------
    living_z = 8.5 if loft else 5.0
    u.light("LivingCeiling", (W / 2, 2.45, living_z), WARM, 1.2, 6.5, shadow=True)
    u.light("EntryCeiling", (kx(1.2), 2.45, 1.4), WARM, 0.6, 3.5)
    u.light("BathCeiling", ((bx0 + bx1) / 2, 2.4, bath_d / 2), COOL, 0.8, 3.0)
    if loft:
        u.light("DiningCeiling", (W / 2, 2.45, 4.8), WARM, 0.6, 4.0)
        u.light("BedCeiling", (W / 2, 2.45, 11.0), WARM, 0.6, 4.0)
    # Probes: the room at the window reaches 1.2 m past the facade (the glass reflects it, as in the apartment).
    room_z0 = 6.0 if loft else bath_d
    u.probe("RoomProbe", (W / 2, 1.3, (room_z0 + D) / 2 + 0.6), (W - T, 2.7, D - room_z0 - T + 1.2), daylight=True)
    if loft:
        u.probe("EntryProbe", (W / 2, 1.3, 3.0), (W - T, 2.7, 6.0 - T))
    else:
        u.probe("EntryProbe", ((ex0 + ex1) / 2, 1.3, bath_d / 2), (ex1 - ex0 - T, 2.7, bath_d - T))
    u.probe("BathProbe", ((bx0 + bx1) / 2, 1.3, bath_d / 2), (bx1 - bx0 - T + 0.2, 2.8, bath_d - T + 0.2), 0.1)

    # --- Entry and the perf path (-Z of a marker = where it looks) -------------------------------------
    u.z.entry("Door", u.p(door, 0, 0.8), u.turn(180))
    for at, look in [((door, 1.7, 0.6), 180), ((W / 2, 1.7, D * 0.45), 180), ((W / 2, 1.7, D - 1.2), 0),
                     ((mx(bath_w / 2), 1.7, 1.2), face_kitchen)]:
        u.z.perf_marker(u.p(*at), (0, u.turn(look), 0))
    return u.z


def build() -> list[Zone]:
    return [build_unit(*spec) for spec in UNITS]


if __name__ == "__main__":
    check = "--check" in sys.argv
    sys.exit(sum(z.save(check=check) for z in build()))
